import { AddressComponent } from './ng2-google-place-classes';
export declare class GooglePlaceService {
    constructor();
    private find(address_components, query, val?);
    street_number(address_components: Array<AddressComponent>): any;
    street(address_components: Array<AddressComponent>): any;
    city(address_components: Array<AddressComponent>): any;
    state(address_components: Array<AddressComponent>): any;
    postal_code(address_components: Array<AddressComponent>): any;
    country(address_components: Array<AddressComponent>): any;
    administrative_area_level_2(address_components: Array<AddressComponent>): any;
    intersection(address_components: Array<AddressComponent>): any;
    political(address_components: Array<AddressComponent>): any;
    administrative_area_level_3(address_components: Array<AddressComponent>): any;
    administrative_area_level_4(address_components: Array<AddressComponent>): any;
    administrative_area_level_5(address_components: Array<AddressComponent>): any;
    colloquial_area(address_components: Array<AddressComponent>): any;
    ward(address_components: Array<AddressComponent>): any;
    sublocality(address_components: Array<AddressComponent>): any;
    sublocality_level_1(address_components: Array<AddressComponent>): any;
    sublocality_level_2(address_components: Array<AddressComponent>): any;
    sublocality_level_3(address_components: Array<AddressComponent>): any;
    sublocality_level_4(address_components: Array<AddressComponent>): any;
    sublocality_level_5(address_components: Array<AddressComponent>): any;
    neighborhood(address_components: Array<AddressComponent>): any;
    premise(address_components: Array<AddressComponent>): any;
    subpremise(address_components: Array<AddressComponent>): any;
    natural_feature(address_components: Array<AddressComponent>): any;
    airport(address_components: Array<AddressComponent>): any;
    park(address_components: Array<AddressComponent>): any;
    point_of_interest(address_components: Array<AddressComponent>): any;
    floor(address_components: Array<AddressComponent>): any;
    establishment(address_components: Array<AddressComponent>): any;
    parking(address_components: Array<AddressComponent>): any;
    post_box(address_components: Array<AddressComponent>): any;
    postal_town(address_components: Array<AddressComponent>): any;
    room(address_components: Array<AddressComponent>): any;
    bus_station(address_components: Array<AddressComponent>): any;
    train_station(address_components: Array<AddressComponent>): any;
    transit_station(address_components: Array<AddressComponent>): any;
    countryIsoCode(): {
        Name: string;
        Code: string;
    }[];
    TypesOptions(): string[];
}
