import { ElementRef, EventEmitter, OnInit } from '@angular/core';
import { GooglePlaceService } from './ng2-google-place-service';
import { Address } from './ng2-google-place-classes';
export declare class GooglePlaceDirective implements OnInit {
    private el;
    private service;
    options: any;
    CountryCodes: EventEmitter<any>;
    setAddress: EventEmitter<any>;
    street_number: EventEmitter<any>;
    postal_code: EventEmitter<any>;
    country: EventEmitter<any>;
    lat: EventEmitter<any>;
    lng: EventEmitter<any>;
    adr_address: EventEmitter<any>;
    formatted_address: EventEmitter<any>;
    name: EventEmitter<any>;
    place_id: EventEmitter<any>;
    types: EventEmitter<any>;
    url: EventEmitter<any>;
    utc_offset: EventEmitter<any>;
    vicinity: EventEmitter<any>;
    photos: EventEmitter<any>;
    street: EventEmitter<any>;
    city: EventEmitter<any>;
    state: EventEmitter<any>;
    district: EventEmitter<any>;
    autocomplete: any;
    trigger: any;
    constructor(el: ElementRef, service: GooglePlaceService);
    ngOnInit(): void;
    invokeEvent(place: Address): void;
}
