import { EventEmitter, ComponentFactoryResolver, ViewContainerRef, OnInit } from '@angular/core';
import { GooglePlaceService } from './ng2-google-place-service';
import { Address } from './ng2-google-place-classes';
export declare class GooglePlaceDirective implements OnInit {
    private service;
    private resolver;
    viewContainerRef: ViewContainerRef;
    options: any;
    ngModelChange: EventEmitter<any>;
    setAddress: EventEmitter<any>;
    street_number: EventEmitter<any>;
    postal_code: EventEmitter<any>;
    country: EventEmitter<any>;
    lat: EventEmitter<any>;
    lng: EventEmitter<any>;
    adr_address: EventEmitter<any>;
    formatted_address: EventEmitter<any>;
    icon: EventEmitter<any>;
    name: EventEmitter<any>;
    place_id: EventEmitter<any>;
    scope: EventEmitter<any>;
    types: EventEmitter<any>;
    url: EventEmitter<any>;
    utc_offset: EventEmitter<any>;
    vicinity: EventEmitter<any>;
    photos: EventEmitter<any>;
    street: EventEmitter<any>;
    intersection: EventEmitter<any>;
    political: EventEmitter<any>;
    colloquial_area: EventEmitter<any>;
    city: EventEmitter<any>;
    ward: EventEmitter<any>;
    state: EventEmitter<any>;
    district: EventEmitter<any>;
    administrative_area_level_3: EventEmitter<any>;
    administrative_area_level_4: EventEmitter<any>;
    administrative_area_level_5: EventEmitter<any>;
    sublocality: EventEmitter<any>;
    sublocality_level_1: EventEmitter<any>;
    sublocality_level_2: EventEmitter<any>;
    sublocality_level_3: EventEmitter<any>;
    sublocality_level_4: EventEmitter<any>;
    sublocality_level_5: EventEmitter<any>;
    neighborhood: EventEmitter<any>;
    premise: EventEmitter<any>;
    subpremise: EventEmitter<any>;
    natural_feature: EventEmitter<any>;
    airport: EventEmitter<any>;
    park: EventEmitter<any>;
    point_of_interest: EventEmitter<any>;
    floor: EventEmitter<any>;
    establishment: EventEmitter<any>;
    parking: EventEmitter<any>;
    post_box: EventEmitter<any>;
    room: EventEmitter<any>;
    postal_town: EventEmitter<any>;
    bus_station: EventEmitter<any>;
    train_station: EventEmitter<any>;
    transit_station: EventEmitter<any>;
    autocomplete: any;
    private el;
    private place;
    constructor(service: GooglePlaceService, resolver: ComponentFactoryResolver, viewContainerRef: ViewContainerRef);
    ngOnInit(): void;
    invokeEvent(place: Address): void;
}
